import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('https://dreamisland.ru/');
  await page.getByRole('banner').getByText('Купить билет').click();
  await page.locator('div').filter({ hasText: /^парк развлечений49 головокружительных аттракционов и 5 шоус 12:00 до 22:00Купить$/ }).getByRole('button').click();
  const iframe = await page.locator('[id="__next"] iframe');
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('radio', { name: ':00 - 22:00' }).check();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('cell', { name: '30 2900₽' }).getByRole('link').click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('radio', { name: ':00 - 22:00' }).check();
  await page.locator('[id="__next"] iframe').contentFrame().locator('.ticket-type__button.plus > .ticket-type__icon > path').first().click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('button', { name: 'Далее' }).click();
  const modal = await page.locator('[id="__next"] iframe').contentFrame().locator('div').filter({ hasText: 'Чтобы воспользоваться бонусами для покупки или начислить бонусы, необходимо авто' }).nth(3).scrollIntoViewIfNeeded();
  await page.locator('[id="__next"] iframe').contentFrame().getByText('Купить без авторизации').click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: 'ivanov@inbox.ru' }).click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: 'ivanov@inbox.ru' }).fill('test@test.test');
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: 'Иван', exact: true }).click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: 'Иван', exact: true }).fill('Фёдор');
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: 'Иванов' }).click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: 'Иванов' }).fill('Фёдоров');
  await page.locator('[id="__next"] iframe').contentFrame().locator('#retry_user_email').click();
  await page.locator('[id="__next"] iframe').contentFrame().locator('#retry_user_email').fill('test@test.test');
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: '+ 7 926 355 70' }).click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('textbox', { name: '+ 7 926 355 70' }).fill('+7 900 000 00 00');
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('listitem').filter({ hasText: 'Я согласен(на) на обработку персональных данных' }).locator('i').click();
  await page.locator('[id="__next"] iframe').contentFrame().getByRole('button', { name: 'Далее' }).click();
  await page.waitForURL(/https:\/\/buy-dreamisland-pay\.server\.paykeeper\.ru\/bill\/\d*/);
  await expect(page).toHaveURL(/https:\/\/buy-dreamisland-pay\.server\.paykeeper\.ru\/bill\/\d*/);
});