name: test_ticket_purchase_ci
on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test     
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: /test-results
          allure_report: /allure-report
          allure_history: /allure-history
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PUBLISH_BRANCH: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: allure-history
